[colors.primary]
background = "#192330"
foreground = "#cdcecf"
dim_foreground = "#aeafb0"
bright_foreground = "#d6d6d7"

[colors.cursor]
text = "#cdcecf"
cursor = "#aeafb0"

[colors.vi_mode_cursor]
text = "#192330"
cursor = "#c94f6d"

[colors.search.matches]
foreground = "#192330"
background = "#dbc074"

[colors.search.focused_match]
foreground = "#192330"
background = "#c94f6d"

[colors.footer_bar]
foreground = "#cdcecf"
background = "#29394f"

[colors.hints.start]
foreground = "#c94f6d"
background = "#192330"

[colors.hints.end]
foreground = "#dbc074"
background = "#192330"

[colors.selection]
text = "#cdcecf"
background = "#2b3b51"

[colors.normal]
black = "#393b44"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
white = "#dfdfe0"

[colors.bright]
black = "#575860"
red = "#d16983"
green = "#8ebaa4"
yellow = "#e0c989"
blue = "#86abdc"
magenta = "#baa1e2"
cyan = "#7ad5d6"
white = "#e4e4e5"

[colors.dim]
black = "#30323a"
red = "#ab435d"
green = "#6e9783"
yellow = "#baa363"
blue = "#6085b6"
magenta = "#8567b6"
cyan = "#54aeb0"
white = "#bebebe"

[[colors.indexed_colors]]
index = 16
color = "#f4a261"

[[colors.indexed_colors]]
index = 17
color = "#d67ad2"

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Never"
shape = "Beam"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[hints]
alphabet = "xwchmuloriaefds"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[[hints.enabled]]
action = "MoveViModeCursor"
regex = ".*"

[hints.enabled.binding]
key = "L"
mods = "Alt"

[[hints.enabled]]
action = "Copy"
regex = "[^ ][^ ]*"

[hints.enabled.binding]
key = "A"
mods = "Alt"

[[hints.enabled]]
action = "Copy"
regex = "[^> ].*?  "

[hints.enabled.binding]
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "'"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mode = "~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "V"
mode = "Vi|~Search"
mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
history = 25000

[window]
decorations = "none"

[window.padding]
x = 4
y = 4
