layouts:
  - tall
  - fullscreen
  - floating
  - wide
  - bsp

window-margins: true
window-margin-size: 5
mouse-follows-focus: true
enables-layout-hud-on-space-change: false
screen-padding-top: 10
screen-padding-bottom: 10
screen-padding-left: 10
screen-padding-right: 10

mod1:
  - command
mod2:
  - command
  - shift

cycle-layout:
  mod: mod2
  key: "c"
cycle-layout-backward:
  mod: mod2
  key: "x"
shrink-main:
  mod: mod1
  key: ","
expand-main:
  mod: mod1
  key: "."
increase-main:
  mod: mod2
  key: "."
decrease-main:
  mod: mod2
  key: ","

# command1: {"mod":"","key":""}
# command2: {"mod":"","key":""}
# command3: {"mod":"","key":""}
# command4: {"mod":"","key":""}

focus-ccw:
  mod: mod1
  key: "k"
focus-cw:
  mod: mod1
  key: "j"
focus-main: {"mod":"","key":""}
  # mod: mod1
  # key: "enter"
focus-screen-ccw:
  mod: mod1
  key: "h"
focus-screen-cw:
  mod: mod1
  key: "l"
swap-screen-ccw:
  mod: mod2
  key: "h"
swap-screen-cw:
  mod: mod2
  key: "l"
swap-ccw:
  mod: mod2
  key: "k"
swap-cw:
  mod: mod2
  key: "j"
swap-main:
  mod: mod1
  key: "enter"
reevaluate-windows: {"mod":"","key":""}
throw-space-left:
  mod: mod2
  key: "p"
throw-space-right:
  mod: mod2
  key: "n"

throw-space-1: {"mod":"","key":""}
throw-space-2: {"mod":"","key":""}
throw-space-3: {"mod":"","key":""}
throw-space-4: {"mod":"","key":""}
throw-space-5: {"mod":"","key":""}
throw-space-6: {"mod":"","key":""}
throw-space-7: {"mod":"","key":""}
throw-space-8: {"mod":"","key":""}
throw-space-9: {"mod":"","key":""}
throw-space-10: {"mod":"","key":""}
focus-screen-1: {"mod":"","key":""}
throw-screen-1: {"mod":"","key":""}
focus-screen-2: {"mod":"","key":""}
throw-screen-2: {"mod":"","key":""}
focus-screen-3: {"mod":"","key":""}
throw-screen-3: {"mod":"","key":""}
focus-screen-4: {"mod":"","key":""}
throw-screen-4: {"mod":"","key":""}

toggle-float:
  mod: mod2
  key: "space"
display-current-layout: {"mod":"","key":""}
toggle-focus-follows-mouse: {"mod":"","key":""}
toggle-tiling: {"mod":"","key":""}

select-tall-layout: {"mod":"","key":""}
  # mod: mod2
  # key: "t"
select-wide-layout: {"mod":"","key":""}
  # mod: mod2
  # key: "w"
select-fullscreen-layout: {"mod":"","key":""}
  # mod: mod2
  # key: "m"
select-column-layout: {"mod":"","key":""}
select-floating-layout: {"mod":"","key":""}
  # mod: mod2
  # key: "x"
select-bsp-layout: {"mod":"","key":""}
  # mod: mod2
  # key: "s"

relaunch-amethyst:
  mod: mod2
  key: "z"
