gui:
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  mainPanelSplitMode: 'horizontal' # one of 'horizontal' | 'flexible' | 'vertical'
  theme:
    lightTheme: false
    activeBorderColor:
    - red
    - bold
    inactiveBorderColor:
    - blue
    optionsTextColor:
    - blue
    selectedLineBgColor:
    - bold
  commitLength:
    show: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: false
git:
  paging:
    colorArg: always
    pager: delta --paging=never --dark --24-bit-color=never
  merging:
    manualCommit: false
  skipHookPrefix: WIP
  autoFetch: true
  overrideGpg: false
  disableForcePushing: false
update:
  method: prompt
  days: 14
reporting: "off"
confirmOnQuit: false
quitOnTopLevelReturn: true
disableStartupPopups: false
os:
  opencommand: $EDITOR {{filename}}
customCommands:
  - key: 'B'
    command: 'hub browse'
    context: 'global'
  - key: 'B'
    command: 'hub browse -- "tree/{{.SelectedLocalBranch.Name}}"'
    context: 'localBranches'
  - key: 'B'
    command: 'hub browse -- "tree/{{.SelectedRemoteBranch.Name}}"'
    context: 'remoteBranches'
  - key: 'B'
    command: 'hub browse -- "commit/{{.SelectedLocalCommit.Sha}}"'
    context: 'commits'
services:
  "github.optum.com": "github:github.optum.com"
