gui:
    expandFocusedSidePanel: true
    mainPanelSplitMode: "horizontal" # horizontal | flexible | vertical
    # enlargedSideViewLocation: "top" # left | top
    theme:
        lightTheme: false
        activeBorderColor:
            - red
            - bold
        inactiveBorderColor:
            - blue
        unstagedChangesColor:
            - blue
    # showListFooter: false
    # showRandomTip: false
git:
    paging:
        colorArg: always
        pager: delta --paging=never --dark --24-bit-color=never
os:
    opencommand: $EDITOR {{filename}}
reporting: "off"
quitOnTopLevelReturn: true
notARepository: 'skip' # prompt | create | skip
customCommands:
    - key: 'B'
      command: 'git ls-remote --get-url | xargs open'
      context: 'global'
