#### Default Options #############################
alias ls="ls -Hp"
alias bc="bc -q"

#### Shortcut ####################################
# alias vim="$EDITOR"
# alias vi="$EDITOR"
alias v="$EDITOR"
alias lf="lfcd"
alias l="lfcd"
alias L="lazygit"
alias pager="$PAGER --paging=always"
alias bat="bat --paging=never"
alias hist="fc -l -ndfD"
alias la="ls -HpA"
alias ll="ls -Hpl"
alias ca="calcurse"
alias ldk="lazydocker"
alias yay="pacapt"
alias cll="printf '\033\143'"
alias loc="tokei -s code"
alias topgrade="topgrade --disable system node pip3 containers rustup cargo yarn gcloud"

#### Configs #####################################
alias .hist="$EDITOR $HISTFILE"
alias .prof="$EDITOR $HOME/.zprofile"
alias .env="$EDITOR $ZDOTDIR/profile.zsh"
alias .alias="$EDITOR $ZDOTDIR/alias.zsh"
alias .zsh="cd $ZDOTDIR && $EDITOR .zshrc"
alias .vim="cd $XDG_CONFIG_HOME/nvim && $EDITOR init.lua"
alias .wez="$EDITOR $XDG_CONFIG_HOME/wezterm/wezterm.lua"
alias .wez="$EDITOR $XDG_CONFIG_HOME/wezterm/wezterm.lua"
