#### Default Options #############################
alias ls="ls -Hp"
alias bc="bc -q"

#### Shortcut ####################################
alias vim="$EDITOR"
alias vi="$EDITOR"
alias v="$EDITOR"
alias lf="lfcd"
alias l="lfcd"
alias g="gitui"
alias k="kubetui"
alias L="lazygit"
alias pager="$PAGER --paging=always"
alias bat="bat --paging=never"
alias hist="fc -l -ndfD"
alias la="ls -HpA"
alias ll="ls -Hpl"
alias ca="calcurse"
alias ldk="lazydocker"
alias yay="pacapt"
alias cll="printf '\033\143'"
alias loc="tokei -s code"
alias top="btm -ufgl --autohide_time --hide_table_gap --mem_as_value"
alias topgrade="topgrade --disable system node pip3 containers"

#### Configs #####################################
alias .zsh="cd $ZDOTDIR"
alias .env="$EDITOR $HOME/.zprofile"
alias .nvim="cd $XDG_CONFIG_HOME/nvim/lua"
alias .hist="$EDITOR $HISTFILE"
alias .conf="cd $XDG_CONFIG_HOME"
